### ISSUE TITLE
Error trying to compile

### ISSUE THREAD

**Issue by trevortomesh** [Piot/enias#1]
Hey! I'm trying to compile your code on Ubuntu 17.10 and I get the following error when trying to run compile.sh

clang: error: no such file or directory: 'external/lib/zany/*.c

I'm assuming there's meant to be another directory?

**Comment by piot** [comment]
Sorry, should be fixed now!

**Comment by trevortomesh** [comment]
Can confirm -- compiles for me now.

**Comment by piot** [comment]
Thank you! Does it run as well? (With the example .prg?)

`./enias examples/hackman/hackman.prg`

**Comment by trevortomesh** [comment]
It works -- but I am not sure what the output is meant to be.

**Comment by piot** [comment]
No, it is very early days for this project. The `hackman.prg` is mainly just testing the sprites and tile background for now. 😊 
Next thing is to include the sound chip.

Thanks for helping out, I appreciate it!

**Comment by trevortomesh** [comment]
No problem! I want to see more fantasy consoles get off the ground!
